#test comment

name: Deployment Pipeline

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install && cd ./frontend && npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run buildfrontend
      - name: Build fail notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ !success() }}
        with:
          details: Build did not succeed.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deploy to Heroku
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'fsopen-exercise-11-20'
          heroku_email: eemeli.paalimaki.work@protonmail.com
          healthcheck: 'https://fsopen-exercise-11-20.herokuapp.com/health'
          rollbackonhealthcheckfailed: true
      - name: New version deploy notification
        uses: rjstone/discord-webhook-notify@v1
        if: |
          success() &&
          github.event_name == 'push' &&
          !contains(toJSON(github.event.commits.*.message), '#skip')
        with:
          severity: info
          details: A new version deployed, hooray!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: New version deploy notification
      uses: rjstone/discord-webhook-notify@v1
      if: |
        success() &&
        github.event_name == 'push' &&
        !contains(toJSON(github.event.commits.*.message), '#skip')
      with:
        severity: info
        details: A new version deployed to Heroku!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
